export const metadata: { [key: string]: string[] } = {
  backgrounds: [
    "Genetic_charts.jpg",
    "Handmade_1.jpg",
    "Handmade_2.png",
    "Handmade_3.png",
    "Handmade_4.jpg",
    "Lincoln.jpg",
  ],
  portraits: ["Test_Portrait.png"],
  layers: [
    "Ripped_paper.png",
    "Anatomy_grid.png",
    "Article_1.png",
    "Cactus.png",
    "Collectors_General_Warning.png",
    "CULT_mag.png",
    "ephemera_clippings.png",
    "Folded_Paper.png",
    "Form_Mag.png",
    "Not_Monday.png",
    "Pump&dump.png",
    "Puzzle_1.png",
    "Rip_1.png",
    "S.png",
    "Slime_Mag.png",
    "Sticker_1.png",
    "Sticker_2.jpg",
    "Sticker_3.png",
    "Sticker_4.png",

    "Wrinkled_Paper.png",
  ],
};
